version: '2'
services:
  web:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
      - ../media:/code/media
    ports:
      - "8007:8000"
    external_links:
      - docker-mysql:db
    network_mode: bridge
